version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=Keshav
      - POSTGRES_PASSWORD=Dadhich@123
      - POSTGRES_DB=guardianai_db
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: